In [1]:
import pandas as pd
import numpy as np

from sklearn.cross_validation import train_test_split
#from sklearn.model_selection import train_test_split

from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.linear_model import SGDClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score, confusion_matrix

from sklearn.semi_supervised import LabelPropagation, LabelSpreading

#from sklearn.model_selection import cross_val_score
from sklearn.cross_validation import cross_val_score

#import time #処理時間の計測用

import os
#ロジスティック回帰、ランダムフォレスト、XGBoostを使用して評価するか
from sklearn.metrics import roc_auc_score

In [2]:
train_data = pd.read_csv("data_mart_171021.csv", encoding="shift-jis", header=0)
y = train_data.iloc[:,3]
X = train_data.iloc[:,[1,2,4]]

In [3]:
X

年齢  性別  s_id
0    68   0     1
1    42   0     1
2    34   0     1
3    88   1     1
4    70   1     1
5    77   1     1
6    50   1     1
7    54   1     1
8    52   1     1
9    60   1     1
10   73   0     1
11    7   0     1
12   68   0     1
13   87   0     1
14   96   0     1
15    6   0     1
16   79   1     1
17   93   0     1
18   26   0     1
19   10   1     2
20    2   0     2
21   32   1     2
22   90   1     2
23   36   1     2
24   42   0     2
25   58   0     2
26   44   0     2
27   19   1     2
28  100   1     2
29   96   0     2
..  ...  ..   ...
70   22   1     4
71   63   0     4
72   12   1     4
73   17   1     4
74   84   1     4
75   76   0     4
76   13   1     4
77   24   1     4
78   36   1     4
79   10   0     4
80   19   0     5
81   80   1     5
82   83   1     5
83   84   1     5
84   80   1     5
85   62   0     5
86   51   0     5
87   43   0     5
88   35   1     5
89   21   0     5
90   35   0     5
91   78   1     5
92   80   1     5
93   36   0     5
94   43   0     5
95    8   1     5
96    5   0     5
97   82   1     5
98   36   0     5
99   63   1     5

[100 rows x 3 columns]

In [4]:
from sklearn.linear_model import LogisticRegression

In [5]:
from sklearn.cross_validation import train_test_split
from sklearn.preprocessing import StandardScaler

In [6]:
import matplotlib.pyplot as plt
import numpy as np

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [8]:
sc = StandardScaler()
X_train_std = sc.fit_transform(X_train)
X_test_std = sc.transform(X_test)

In [25]:
import collections
print(collections.Counter(y_test))

Counter({0: 16, 1: 14})


In [10]:
X_train_std

array([[-0.86578981, -1.02899151, -0.0103645 ],
       [ 1.12865168,  0.97182532,  1.44066593],
       [ 1.03214645,  0.97182532,  1.44066593],
       [ 1.45033579, -1.02899151, -1.46139493],
       [-0.99446345,  0.97182532, -0.0103645 ],
       [-1.15530551,  0.97182532,  0.71515071],
       [ 0.09926253, -1.02899151,  1.44066593],
       [-1.05880027,  0.97182532, -0.0103645 ],
       [-0.76928457,  0.97182532,  0.71515071],
       [ 0.51745187, -1.02899151, -0.73587972],
       [-0.93012663, -1.02899151,  1.44066593],
       [-1.38048438, -1.02899151,  0.71515071],
       [-1.50915803,  0.97182532, -0.0103645 ],
       [ 1.16082009,  0.97182532,  0.71515071],
       [ 0.45311505, -1.02899151,  1.44066593],
       [-1.28397915,  0.97182532,  1.44066593],
       [-1.05880027,  0.97182532, -0.73587972],
       [-0.70494775, -1.02899151, -1.46139493],
       [ 0.64612551, -1.02899151, -1.46139493],
       [ 0.74263075, -1.02899151, -0.73587972],
       [-1.34831597, -1.02899151, -1.461

In [11]:
lr = LogisticRegression()
lr.fit(X_train_std, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [12]:
print (lr.predict(X_test_std))

[1 1 1 1 0 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1]


In [13]:
print (lr.predict_proba(X_test_std))

[[ 0.27759791  0.72240209]
 [ 0.3983421   0.6016579 ]
 [ 0.32829714  0.67170286]
 [ 0.48638441  0.51361559]
 [ 0.54181587  0.45818413]
 [ 0.32697969  0.67302031]
 [ 0.36749251  0.63250749]
 [ 0.46301737  0.53698263]
 [ 0.42951093  0.57048907]
 [ 0.37178981  0.62821019]
 [ 0.35351976  0.64648024]
 [ 0.27022482  0.72977518]
 [ 0.30170214  0.69829786]
 [ 0.52031262  0.47968738]
 [ 0.38630745  0.61369255]
 [ 0.4177392   0.5822608 ]
 [ 0.44040151  0.55959849]
 [ 0.39686464  0.60313536]
 [ 0.36177616  0.63822384]
 [ 0.44772008  0.55227992]
 [ 0.54183143  0.45816857]
 [ 0.42347577  0.57652423]
 [ 0.32829714  0.67170286]
 [ 0.29396235  0.70603765]
 [ 0.41894897  0.58105103]
 [ 0.37638837  0.62361163]
 [ 0.62120161  0.37879839]
 [ 0.43860255  0.56139745]
 [ 0.4556706   0.5443294 ]
 [ 0.32558237  0.67441763]]


In [14]:
print (lr.score(X_test_std, y_test))

0.533333333333


In [15]:
lr.predict_proba(X_test)[:,1]

array([  1.39973644e-01,   3.90289375e-03,   1.13129736e-06,
         3.82654868e-04,   3.12569692e-05,   4.24040273e-01,
         2.82279169e-03,   1.32437769e-08,   7.31449046e-05,
         1.95887382e-05,   5.99260090e-01,   6.28666819e-03,
         4.24010559e-03,   4.57800248e-04,   2.87884103e-06,
         6.81599548e-01,   1.07624070e-01,   4.72398155e-03,
         6.05878581e-03,   9.01172349e-08,   2.53460906e-03,
         1.57494668e-04,   1.13129736e-06,   1.32768479e-02,
         3.44444193e-06,   6.50248236e-02,   9.79927889e-08,
         2.31487834e-05,   5.90306358e-01,   1.66010574e-06])

In [16]:
print("LogisticRegression AUC =", roc_auc_score(y_test, lr.predict_proba(X_test)[:,1]))

LogisticRegression AUC = 0.477678571429


In [17]:
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import auc
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc

probas_ = lr.predict_proba(X_test)
fpr, tpr, thresholds = roc_curve(y_test, probas_[:, 1])
roc_auc_area = auc(fpr, tpr)

# pl.clf()

plt.plot(fpr, tpr, label='ROC curve (area = %0.2f)' % roc_auc_area)
plt.plot([0, 1], [0, 1], 'k--') # 45度線の描画
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.0])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver operating characteristic')
plt.legend(loc="lower right")

In [19]:
plt.savefig("ROC_Curve.png")

In [20]:
!pip install xgboost

    100% |████████████████████████████████| 1.2MB 265kB/s 
  Running setup.py install for xgboost ... - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | done


In [25]:
!python --version
#Python 3.5.1

Python 3.5.1


In [24]:
!pyenv versions

  system
  2.7.8
  3.4.2
* 3.5.1 (set by PYENV_VERSION environment variable)
  anaconda3-2.4.0
  miniconda3-3.7.0


In [26]:
import xgboost as xgb

In [29]:
mod = xgb.XGBRegressor()
mod.fit(X_train_std, y_train)

XGBRegressor(base_score=0.5, colsample_bylevel=1, colsample_bytree=1, gamma=0,
       learning_rate=0.1, max_delta_step=0, max_depth=3,
       min_child_weight=1, missing=None, n_estimators=100, nthread=-1,
       objective='reg:linear', reg_alpha=0, reg_lambda=1,
       scale_pos_weight=1, seed=0, silent=True, subsample=1)

In [30]:
print (mod.score(X_test_std, y_test))

-0.396543900463


In [31]:
mod.predict(X_test_std)

array([ 0.94265962,  0.90465713, -0.11651236,  0.32703716,  0.14635158,
        0.20177671,  0.90815282,  0.63212788,  0.39251804,  0.34072322,
        0.06389973,  0.83894002,  0.54430199,  0.44050118,  0.20360005,
        0.90391684,  0.44036636,  0.0339199 ,  0.90273595,  0.90498245,
        0.40148956,  0.0339199 ,  0.21036568,  0.54395586,  0.82035488,
        0.81267238,  0.90815282,  0.52245367,  0.70793509,  0.39251804], dtype=float32)

In [35]:
y_train_pred = mod.predict(X_train_std)
y_test_pred = mod.predict(X_test_std)


In [36]:
# MSE
from sklearn.metrics import mean_squared_error
print('MSE train : %.3f, test : %.3f' % (mean_squared_error(y_train, y_train_pred), mean_squared_error(y_test, y_test_pred)) )


MSE train : 0.054, test : 0.349


In [37]:
# R^2
from sklearn.metrics import r2_score
print('R^2 train : %.3f, test : %.3f' % (r2_score(y_train, y_train_pred), r2_score(y_test, y_test_pred)) )



R^2 train : 0.780, test : -0.397


In [38]:
# 出力
print('MSE train : %.3f, test : %.3f' % (mean_squared_error(y_train, y_train_pred), mean_squared_error(y_test, y_test_pred)) )
print('R^2 train : %.3f, test : %.3f' % (r2_score(y_train, y_train_pred), r2_score(y_test, y_test_pred)) )


MSE train : 0.054, test : 0.349
R^2 train : 0.780, test : -0.397


In [45]:
print("LogisticRegression AUC =", roc_auc_score(y_test, mod.predict_proba(X_test)[:,1]))

AttributeError: 'XGBRegressor' object has no attribute 'predict_proba'

In [42]:
!pip install lightgbm

    100% |████████████████████████████████| 604kB 488kB/s 


In [44]:
import lightgbm as lgb
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import KFold, train_test_split

OSError: dlopen(/Users/takumasaito/.pyenv/versions/3.5.1/lib/python3.5/site-packages/lightgbm/lib_lightgbm.so, 6): Library not loaded: /usr/local/opt/gcc/lib/gcc/7/libgomp.1.dylib
  Referenced from: /Users/takumasaito/.pyenv/versions/3.5.1/lib/python3.5/site-packages/lightgbm/lib_lightgbm.so
  Reason: image not found