In [4]:
import pandas as pd
import numpy as np

from sklearn.cross_validation import train_test_split
#from sklearn.model_selection import train_test_split

from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.linear_model import SGDClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score, confusion_matrix

from sklearn.semi_supervised import LabelPropagation, LabelSpreading

#from sklearn.model_selection import cross_val_score
from sklearn.cross_validation import cross_val_score

#import time #処理時間の計測用

import os
#ロジスティック回帰、ランダムフォレスト、XGBoostを使用して評価するか
from sklearn.metrics import roc_auc_score

In [3]:
!python --version

Python 3.6.1 :: Anaconda 4.4.0 (64-bit)


In [6]:
train_data = pd.read_csv("data_171104.csv", encoding="shift-jis", header=0)
train_data

id  職員id   続柄    生年  企業コード有無   性別  成約有無_Sum  成約有無_Max   成約数  \
0          1.0   1.0  1.0  64.0      1.0  1.0       0.0       0.0   4.0   
1          2.0   1.0  1.0  62.0      1.0  1.0       0.0       0.0  33.0   
2          3.0  27.0  1.0  87.0      1.0  1.0       0.0       0.0   4.0   
3          4.0  27.0  1.0  66.0      1.0  1.0       0.0       0.0   2.0   
4          5.0   7.0  1.0  78.0      1.0  1.0       0.0       0.0   7.0   
5          6.0   1.0  1.0  68.0      1.0  1.0       0.0       0.0  25.0   
6          7.0  12.0  1.0  50.0      1.0  1.0       0.0       0.0  23.0   
7          8.0  27.0  1.0  87.0      1.0  1.0       0.0       0.0   7.0   
8          9.0  17.0  1.0  56.0      0.0  1.0       0.0       0.0  24.0   
9         10.0  22.0  1.0  92.0      0.0  2.0       0.0       0.0   3.0   
10        11.0   8.0  1.0  81.0      0.0  1.0       0.0       0.0   1.0   
11        12.0  22.0  1.0  51.0      1.0  1.0       0.0       0.0   3.0   
12        13.0  17.0  1.0  62.0      1.0  1.0       0.0       0.0   3.0   
13        14.0  24.0  1.0  54.0      1.0  1.0       0.0       0.0   8.0   
14        15.0  18.0  1.0  69.0      1.0  1.0       0.0       0.0   2.0   
15        16.0  26.0  1.0  83.0      0.0  1.0       0.0       0.0  18.0   
16        17.0  23.0  1.0  62.0      1.0  1.0       0.0       0.0   5.0   
17        18.0   1.0  1.0  55.0      0.0  1.0       0.0       0.0   8.0   
18        19.0   1.0  2.0  66.0      0.0  2.0       0.0       0.0   1.0   
19        20.0  17.0  1.0  55.0      0.0  2.0       0.0       0.0   1.0   
20        21.0   1.0  2.0  66.0      0.0  2.0       0.0       0.0   2.0   
21        22.0  17.0  1.0  55.0      0.0  2.0       0.0       0.0   6.0   
22        23.0  23.0  1.0  68.0      1.0  1.0       0.0       0.0   2.0   
23        24.0  15.0  1.0  63.0      1.0  1.0       0.0       0.0   2.0   
24        25.0  10.0  1.0  63.0      1.0  1.0       0.0       0.0   2.0   
25        26.0   1.0  1.0  67.0      1.0  1.0       0.0       0.0  30.0   
26        27.0   1.0  1.0  55.0      0.0  1.0       1.0       1.0  28.0   
27        28.0  10.0  1.0  67.0      1.0  2.0       0.0       0.0  15.0   
28        29.0   8.0  1.0  67.0      1.0  2.0       0.0       0.0  15.0   
29        30.0  25.0  2.0  41.0      0.0  2.0       0.0       0.0  13.0   
...        ...   ...  ...   ...      ...  ...       ...       ...   ...   
24380  24381.0  28.0  1.0  76.0      1.0  1.0       0.0       0.0   1.0   
24381  24382.0  16.0  1.0  91.0      1.0  2.0       0.0       0.0   1.0   
24382  24383.0  18.0  1.0  81.0      0.0  1.0       0.0       0.0   2.0   
24383  24384.0  23.0  1.0  85.0      1.0  1.0       0.0       0.0   1.0   
24384  24385.0  26.0  1.0  71.0      1.0  1.0       0.0       0.0   2.0   
24385  24386.0  10.0  1.0  73.0      0.0  1.0       0.0       0.0   1.0   
24386  24387.0  25.0  1.0  73.0      0.0  1.0       0.0       0.0   1.0   
24387  24388.0  24.0  1.0  43.0      1.0  1.0       0.0       0.0   4.0   
24388  24389.0  28.0  1.0  78.0      1.0  1.0       0.0       0.0   2.0   
24389  24390.0   6.0  1.0   0.0      1.0  0.0       0.0       0.0   5.0   
24390  24391.0   2.0  1.0   0.0      1.0  0.0       0.0       0.0   5.0   
24391  24392.0  16.0  1.0  47.0      1.0  1.0       0.0       0.0   2.0   
24392  24393.0   4.0  1.0  63.0      0.0  1.0       0.0       0.0   2.0   
24393  24394.0  10.0  1.0  74.0      0.0  2.0       0.0       0.0   5.0   
24394  24395.0  20.0  1.0  74.0      0.0  2.0       0.0       0.0   5.0   
24395  24396.0  13.0  1.0  63.0      1.0  1.0       0.0       0.0   4.0   
24396  24397.0  22.0  1.0  84.0      1.0  2.0       0.0       0.0   2.0   
24397  24398.0   1.0  1.0  64.0      1.0  1.0       0.0       0.0   1.0   
24398  24399.0  18.0  1.0  83.0      0.0  1.0       0.0       0.0   3.0   
24399  24400.0   4.0  1.0   0.0      1.0  0.0       0.0       0.0   3.0   
24400  24401.0   2.0  1.0   0.0      1.0  0.0       0.0       0.0   3.0   
24401  24402.0  27.0  1.0  64.0      

In [101]:
y = train_data.iloc[:24407,7]
X = train_data.iloc[:24407,[1, 2, 3, 4, 5]]

In [189]:
y

0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
5        0.0
6        0.0
7        0.0
8        0.0
9        0.0
10       0.0
11       0.0
12       0.0
13       0.0
14       0.0
15       0.0
16       0.0
17       0.0
18       0.0
19       0.0
20       0.0
21       0.0
22       0.0
23       0.0
24       0.0
25       0.0
26       0.0
27       0.0
28       0.0
29       0.0
        ... 
24377    0.0
24378    0.0
24379    0.0
24380    0.0
24381    0.0
24382    0.0
24383    0.0
24384    0.0
24385    0.0
24386    0.0
24387    0.0
24388    0.0
24389    0.0
24390    0.0
24391    0.0
24392    0.0
24393    0.0
24394    0.0
24395    0.0
24396    0.0
24397    0.0
24398    0.0
24399    0.0
24400    0.0
24401    0.0
24402    0.0
24403    0.0
24404    0.0
24405    0.0
24406    0.0
Name: 成約有無_Max, dtype: float64

In [103]:
import collections
print(collections.Counter(y))

Counter({0.0: 23428, 1.0: 979})


In [194]:
X

職員id   続柄    生年  企業コード有無   性別
0       1.0  1.0  64.0      1.0  1.0
1       1.0  1.0  62.0      1.0  1.0
2      27.0  1.0  87.0      1.0  1.0
3      27.0  1.0  66.0      1.0  1.0
4       7.0  1.0  78.0      1.0  1.0
5       1.0  1.0  68.0      1.0  1.0
6      12.0  1.0  50.0      1.0  1.0
7      27.0  1.0  87.0      1.0  1.0
8      17.0  1.0  56.0      0.0  1.0
9      22.0  1.0  92.0      0.0  2.0
10      8.0  1.0  81.0      0.0  1.0
11     22.0  1.0  51.0      1.0  1.0
12     17.0  1.0  62.0      1.0  1.0
13     24.0  1.0  54.0      1.0  1.0
14     18.0  1.0  69.0      1.0  1.0
15     26.0  1.0  83.0      0.0  1.0
16     23.0  1.0  62.0      1.0  1.0
17      1.0  1.0  55.0      0.0  1.0
18      1.0  2.0  66.0      0.0  2.0
19     17.0  1.0  55.0      0.0  2.0
20      1.0  2.0  66.0      0.0  2.0
21     17.0  1.0  55.0      0.0  2.0
22     23.0  1.0  68.0      1.0  1.0
23     15.0  1.0  63.0      1.0  1.0
24     10.0  1.0  63.0      1.0  1.0
25      1.0  1.0  67.0      1.0  1.0
26      1.0  1.0  55.0      0.0  1.0
27     10.0  1.0  67.0      1.0  2.0
28      8.0  1.0  67.0      1.0  2.0
29     25.0  2.0  41.0      0.0  2.0
...     ...  ...   ...      ...  ...
24377  18.0  1.0  44.0      0.0  2.0
24378  13.0  1.0  64.0      1.0  1.0
24379   6.0  1.0  76.0      0.0  1.0
24380  28.0  1.0  76.0      1.0  1.0
24381  16.0  1.0  91.0      1.0  2.0
24382  18.0  1.0  81.0      0.0  1.0
24383  23.0  1.0  85.0      1.0  1.0
24384  26.0  1.0  71.0      1.0  1.0
24385  10.0  1.0  73.0      0.0  1.0
24386  25.0  1.0  73.0      0.0  1.0
24387  24.0  1.0  43.0      1.0  1.0
24388  28.0  1.0  78.0      1.0  1.0
24389   6.0  1.0   0.0      1.0  0.0
24390   2.0  1.0   0.0      1.0  0.0
24391  16.0  1.0  47.0      1.0  1.0
24392   4.0  1.0  63.0      0.0  1.0
24393  10.0  1.0  74.0      0.0  2.0
24394  20.0  1.0  74.0      0.0  2.0
24395  13.0  1.0  63.0      1.0  1.0
24396  22.0  1.0  84.0      1.0  2.0
24397   1.0  1.0  64.0      1.0  1.0
24398  18.0  1.0  83.0      0.0  1.0
24399   4.0  1.0   0.0      1.0  0.0
24400   2.0  1.0   0.0      1.0  0.0
24401  27.0  1.0  64.0      1.0  1.0
24402  12.0  1.0  54.0      0.0  2.0
24403   4.0  1.0  62.0      1.0  1.0
24404  28.0  1.0  76.0      1.0  1.0
24405  22.0  1.0  51.0      0.0  1.0
24406  27.0  1.0  68.0      0.0  1.0

[24407 rows x 5 columns]

職員id   続柄    生年  企業コード有無   性別  成約有無_Max
0       8.0  1.0  78.0      0.0  1.0       0.0
1      22.0  2.0  66.0      1.0  2.0       0.0
2      22.0  1.0  74.0      1.0  1.0       0.0
3       1.0  1.0  74.0      1.0  1.0       0.0
4      18.0  1.0  74.0      0.0  2.0       0.0
5      23.0  1.0  64.0      0.0  2.0       0.0
6       1.0  1.0  61.0      1.0  1.0       0.0
7      28.0  1.0  86.0      0.0  1.0       0.0
8       7.0  1.0  67.0      1.0  1.0       0.0
9      19.0  1.0  66.0      1.0  1.0       0.0
10     27.0  1.0  58.0      0.0  1.0       0.0
11     17.0  1.0  64.0      1.0  1.0       0.0
12     17.0  1.0  70.0      1.0  1.0       0.0
13      2.0  1.0   0.0      1.0  0.0       0.0
14     19.0  1.0  74.0      1.0  1.0       0.0
15     13.0  1.0  69.0      1.0  1.0       0.0
16     13.0  1.0  49.0      1.0  1.0       0.0
17     18.0  1.0  66.0      1.0  1.0       0.0
18      2.0  1.0  51.0      0.0  1.0       0.0
19     19.0  1.0  63.0      1.0  2.0       0.0
20     13.0  1.0  77.0      0.0  2.0       0.0
21     10.0  1.0  43.0      0.0  2.0       0.0
22     13.0  1.0  56.0      1.0  1.0       0.0
23     28.0  1.0  61.0      1.0  1.0       0.0
24     16.0  1.0  58.0      1.0  1.0       0.0
25     23.0  3.0  96.0      0.0  2.0       0.0
26     13.0  1.0  61.0      1.0  1.0       0.0
27     13.0  1.0  75.0      1.0  2.0       0.0
28     23.0  1.0  81.0      0.0  2.0       0.0
29     23.0  1.0  76.0      1.0  1.0       0.0
...     ...  ...   ...      ...  ...       ...
24377  25.0  1.0  67.0      1.0  1.0       0.0
24378   1.0  1.0  68.0      1.0  1.0       0.0
24379   3.0  1.0  78.0      1.0  1.0       0.0
24380  11.0  1.0  64.0      1.0  2.0       0.0
24381  26.0  1.0  59.0      1.0  2.0       0.0
24382  12.0  1.0  78.0      1.0  1.0       0.0
24383   6.0  1.0  59.0      1.0  1.0       0.0
24384  26.0  1.0  52.0      1.0  1.0       0.0
24385  16.0  1.0  65.0      1.0  1.0       0.0
24386  13.0  1.0  72.0      1.0  1.0       0.0
24387  19.0  2.0  61.0      0.0  2.0       0.0
24388   6.0  1.0  65.0      1.0  1.0       0.0
24389  27.0  2.0  68.0      0.0  2.0       0.0
24390   6.0  1.0  88.0      1.0  1.0       0.0
24391  26.0  1.0  68.0      1.0  1.0       0.0
24392   8.0  1.0  61.0      0.0  2.0       0.0
24393  23.0  1.0  67.0      1.0  1.0       0.0
24394  23.0  1.0  67.0      0.0  2.0       0.0
24395   4.0  1.0  80.0      1.0  1.0       0.0
24396  24.0  1.0  45.0      0.0  1.0       0.0
24397  19.0  1.0  60.0      1.0  1.0       0.0
24398  13.0  1.0  81.0      1.0  1.0       0.0
24399  20.0  1.0  73.0      1.0  1.0       0.0
24400  27.0  1.0  86.0      1.0  1.0       0.0
24401   8.0  1.0  66.0      1.0  1.0       0.0
24402   2.0  1.0  71.0      1.0  1.0       0.0
24403  14.0  1.0  60.0      0.0  2.0       0.0
24404  21.0  1.0  71.0      1.0  1.0       0.0
24405  19.0  1.0  85.0      0.0  2.0       0.0
24406  12.0  1.0  60.0      0.0  1.0       0.0

[24407 rows x 6 columns]

In [218]:
x = X.reindex(np.random.permutation(X.index)).reset_index(drop=True)
pd.concat([x, y], axis=1)
print(np.average(prob_pos_sigmoid, axis=0))

0.105598274168


In [197]:
#y
y.where(y >= 1)

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
5       NaN
6       NaN
7       NaN
8       NaN
9       NaN
10      NaN
11      NaN
12      NaN
13      NaN
14      NaN
15      NaN
16      NaN
17      NaN
18      NaN
19      NaN
20      NaN
21      NaN
22      NaN
23      NaN
24      NaN
25      NaN
26      NaN
27      NaN
28      NaN
29      NaN
         ..
24377   NaN
24378   NaN
24379   NaN
24380   NaN
24381   NaN
24382   NaN
24383   NaN
24384   NaN
24385   NaN
24386   NaN
24387   NaN
24388   NaN
24389   NaN
24390   NaN
24391   NaN
24392   NaN
24393   NaN
24394   NaN
24395   NaN
24396   NaN
24397   NaN
24398   NaN
24399   NaN
24400   NaN
24401   NaN
24402   NaN
24403   NaN
24404   NaN
24405   NaN
24406   NaN
Name: 成約有無_Max, dtype: float64

In [58]:
from sklearn.linear_model import LogisticRegression

In [59]:
#from sklearn.cross_validation import train_test_split
from sklearn.preprocessing import StandardScaler

In [60]:
import matplotlib.pyplot as plt
import numpy as np

In [104]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state = 150)

In [105]:
sc = StandardScaler()
X_train_std = sc.fit_transform(X_train)
X_test_std = sc.transform(X_test)

In [106]:
X_train_std

array([[-0.26848764, -0.25753059,  0.2005941 ,  0.80108997, -0.57288321],
       [ 1.12246101,  2.65518219,  0.08620803, -1.24829923,  1.3529603 ],
       [ 0.23731187, -0.25753059,  1.45884093,  0.80108997, -0.57288321],
       ..., 
       [ 0.11086199, -0.25753059,  0.88691055, -1.24829923,  1.3529603 ],
       [-1.78588618, -0.25753059, -0.54291539,  0.80108997, -0.57288321],
       [-1.15363679, -0.25753059,  0.08620803,  0.80108997, -0.57288321]])

In [107]:
lr = LogisticRegression(max_iter=30000)
lr.fit(X_train_std, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=30000, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [108]:
print (lr.predict(X_test_std))

[ 0.  0.  0. ...,  0.  0.  0.]


In [109]:
print (lr.predict_proba(X_test_std))

[[ 0.99700989  0.00299011]
 [ 0.98097037  0.01902963]
 [ 0.95454375  0.04545625]
 ..., 
 [ 0.9617231   0.0382769 ]
 [ 0.93295595  0.06704405]
 [ 0.96553192  0.03446808]]


In [110]:
print (lr.score(X_test_std, y_test))

0.962447084528


In [111]:
tmp = lr.predict_proba(X_test_std)[:,1]

In [112]:
tmp

array([ 0.00299011,  0.01902963,  0.04545625, ...,  0.0382769 ,
        0.06704405,  0.03446808])

In [113]:
#y_test_tmp = label_binarize(y_test, classes=[0, 1, 2, 3])
#tmp_tmp = label_binarize(tmp, classes=[0, 1, 2, 3])

In [114]:
#from sklearn.preprocessing import label_binarize

In [115]:
#len(lr.predict_proba(X_test_std)[:,1])

In [116]:
#len(label_binarize(y_test, classes=[0,1]))

In [181]:
print("LogisticRegression AUC =", roc_auc_score(y_test, tmp))

LogisticRegression AUC = 0.678475905479


In [168]:
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import auc
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc

probas_ = mod.predict_proba(X_test_std)
fpr, tpr, thresholds = roc_curve(y_test, probas_[:, 1])
roc_auc_area = auc(fpr, tpr)

# pl.clf()

plt.plot(fpr, tpr, label='ROC curve (area = %0.2f)' % roc_auc_area)
plt.plot([0, 1], [0, 1], 'k--') # 45度線の描画
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.0])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver operating characteristic')
plt.legend(loc="lower right")

In [169]:
plt.savefig("ROC_Curve_xgb.png")

In [170]:
train_data = pd.read_csv("data_mart_171021.csv", encoding="shift-jis", header=0)
y_sid = train_data.iloc[:,51]
X_sid = train_data.iloc[:,[3, 4, 6, 9]]

y_sid = y_sid.where(y_sid < 1, 1)
X_train, X_test, y_train, y_test = train_test_split(X_sid, y_sid, test_size=0.3, random_state = 130)

sc = StandardScaler()
X_train_std = sc.fit_transform(X_train)
X_test_std = sc.transform(X_test)

lr = LogisticRegression(max_iter=30000)
lr.fit(X_train_std, y_train)

print (lr.score(X_test_std, y_test))

tmp = lr.predict_proba(X_test_std)[:,1]

print("LogisticRegression AUC =", roc_auc_score(y_test, tmp))


0.960262187628
LogisticRegression AUC = 0.652951016267


In [193]:
train_data = pd.read_csv("data_mart_171021.csv", encoding="shift-jis", header=0)
train_data = train_data.loc[(train_data.氏名id == 18)]
y_each = train_data.iloc[:,51]
X_each = train_data.iloc[:,[4, 6, 9]]

y_each = y_each.where(y_each < 1, 1)
X_train, X_test, y_train, y_test = train_test_split(X_each, y_each, test_size=0.3, random_state = 130)

sc = StandardScaler()
X_train_std = sc.fit_transform(X_train)
X_test_std = sc.transform(X_test)

lr = LogisticRegression(max_iter=30000)
lr.fit(X_train_std, y_train)

print (lr.score(X_test_std, y_test))

tmp = lr.predict_proba(X_test)[:,1]

print("LogisticRegression AUC =", roc_auc_score(y_test, tmp))


0.974522292994
LogisticRegression AUC = 0.629901960784


In [32]:
!pip install xgboost

No files/directories in C:\Users\JISEDA~1\AppData\Local\Temp\pip-build-cg5jlrl3\xgboost\pip-egg-info (from PKG-INFO)


In [25]:
!python --version
#Python 3.5.1

Python 3.5.1


In [24]:
!pyenv versions

  system
  2.7.8
  3.4.2
* 3.5.1 (set by PYENV_VERSION environment variable)
  anaconda3-2.4.0
  miniconda3-3.7.0


In [52]:
import xgboost as xgb

In [175]:
mod.get_params

<bound method XGBModel.get_params of XGBClassifier(base_score=0.5, colsample_bylevel=1, colsample_bytree=1,
       gamma=0, learning_rate=0.1, max_delta_step=0, max_depth=3,
       min_child_weight=1, missing=None, n_estimators=100, nthread=-1,
       objective='binary:logistic', reg_alpha=0, reg_lambda=1,
       scale_pos_weight=1, seed=0, silent=True, subsample=1)>

In [118]:
mod = xgb.XGBClassifier()
mod.fit(X_train_std, y_train, eval_set=[(X_train_std, y_train), (X_test_std, y_test)], \
                  eval_metric='auc', early_stopping_rounds = 50)

[0]	validation_0-auc:0.631792	validation_1-auc:0.650809
Multiple eval metrics have been passed: 'validation_1-auc' will be used for early stopping.

Will train until validation_1-auc hasn't improved in 50 rounds.
[1]	validation_0-auc:0.636126	validation_1-auc:0.657571
[2]	validation_0-auc:0.639731	validation_1-auc:0.656242
[3]	validation_0-auc:0.651296	validation_1-auc:0.67434
[4]	validation_0-auc:0.668638	validation_1-auc:0.675892
[5]	validation_0-auc:0.667926	validation_1-auc:0.677068
[6]	validation_0-auc:0.667699	validation_1-auc:0.676675
[7]	validation_0-auc:0.668131	validation_1-auc:0.675229
[8]	validation_0-auc:0.668714	validation_1-auc:0.677962
[9]	validation_0-auc:0.66978	validation_1-auc:0.677075
[10]	validation_0-auc:0.673238	validation_1-auc:0.676365
[11]	validation_0-auc:0.670203	validation_1-auc:0.677195
[12]	validation_0-auc:0.673718	validation_1-auc:0.676339
[13]	validation_0-auc:0.67393	validation_1-auc:0.676591
[14]	validation_0-auc:0.67369	validation_1-auc:0.67661
[15

XGBClassifier(base_score=0.5, colsample_bylevel=1, colsample_bytree=1,
       gamma=0, learning_rate=0.1, max_delta_step=0, max_depth=3,
       min_child_weight=1, missing=None, n_estimators=100, nthread=-1,
       objective='binary:logistic', reg_alpha=0, reg_lambda=1,
       scale_pos_weight=1, seed=0, silent=True, subsample=1)

In [119]:
print (mod.score(X_test_std, y_test))

0.962583640584


In [120]:
mod.predict(X_test_std)

array([ 0.,  0.,  0., ...,  0.,  0.,  0.])

In [121]:
y_pred = mod.predict_proba(X_test_std)[:,1]
roc_auc_score(y_test,y_pred)

0.69624264781756262

In [219]:
print(np.average(y_pred, axis=0))

0.041489


In [81]:
y_train_pred = mod.predict(X_train_std)
y_test_pred = mod.predict(X_test_std)


In [82]:
# MSE
from sklearn.metrics import mean_squared_error
print('MSE train : %.3f, test : %.3f' % (mean_squared_error(y_train, y_train_pred), mean_squared_error(y_test, y_test_pred)) )


MSE train : 0.037, test : 0.038


In [37]:
# R^2
from sklearn.metrics import r2_score
print('R^2 train : %.3f, test : %.3f' % (r2_score(y_train, y_train_pred), r2_score(y_test, y_test_pred)) )



R^2 train : 0.780, test : -0.397


In [38]:
# 出力
print('MSE train : %.3f, test : %.3f' % (mean_squared_error(y_train, y_train_pred), mean_squared_error(y_test, y_test_pred)) )
print('R^2 train : %.3f, test : %.3f' % (r2_score(y_train, y_train_pred), r2_score(y_test, y_test_pred)) )


MSE train : 0.054, test : 0.349
R^2 train : 0.780, test : -0.397


In [129]:
from sklearn.svm import SVC

In [137]:
clf = SVC(C=1.0 , probability = True)

In [138]:
clf.fit(X_train_std, y_train) 

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=True, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [139]:
print (clf.score(X_test_std, y_test))

0.962447084528


In [140]:
print("SVC AUC =", roc_auc_score(y_test, clf.predict_proba(X_test_std)[:,1]))

LogisticRegression AUC = 0.511259157982


In [148]:
plt.style.use('ggplot')
plt_impotance = xgb.plot_importance(mod)
plt_impotance

In [145]:
print('Feature Importances:')
for feat in ['feature_names']:
    print('\t{0:10s} : {1:>12.4f}'.format(feat, fti[feat]))

AttributeError: 'AxesSubplot' object has no attribute 'savefig'

In [151]:
mod.feature_importances_

array([ 0.3305369 ,  0.11409396,  0.4295302 ,  0.04362416,  0.08221477], dtype=float32)

In [157]:
test_data = pd.read_csv("testData_171104.csv", encoding="shift-jis", header=0)
test_data

id  職員id  続柄  生年  企業コード有無  性別
0   30000     1   1  77        1   1
1   30001     2   1  77        1   1
2   30002     3   1  77        1   1
3   30003     4   1  77        1   1
4   30004     5   1  77        1   1
5   30005     6   1  77        1   1
6   30006     7   1  77        1   1
7   30007     8   1  77        1   1
8   30008     9   1  77        1   1
9   30009    10   1  77        1   1
10  30010    11   1  77        1   1
11  30011    12   1  77        1   1
12  30012    13   1  77        1   1
13  30013    14   1  77        1   1
14  30014    15   1  77        1   1
15  30015    16   1  77        1   1
16  30016    17   1  77        1   1
17  30017    18   1  77        1   1
18  30018    19   1  77        1   1
19  30019    20   1  77        1   1
20  30020    21   1  77        1   1
21  30021    22   1  77        1   1
22  30022    23   1  77        1   1
23  30023    24   1  77        1   1
24  30024    25   1  77        1   1
25  30025    26   1  77        1   1
26  30026    27   1  77        1   1
27  30027    28   1  77        1   1
28  30028     1   1  97        1   1
29  30029     2   1  97        1   1
..    ...   ...  ..  ..      ...  ..
55  30055    28   1  97        1   1
56  30056    28   1  84        0   1
57  30057     1   1  57        0   2
58  30058     2   1  57        0   2
59  30059     3   1  57        0   2
60  30060     4   1  57        0   2
61  30061     5   1  57        0   2
62  30062     6   1  57        0   2
63  30063     7   1  57        0   2
64  30064     8   1  57        0   2
65  30065     9   1  57        0   2
66  30066    10   1  57        0   2
67  30067    11   1  57        0   2
68  30068    12   1  57        0   2
69  30069    13   1  57        0   2
70  30070    14   1  57        0   2
71  30071    15   1  57        0   2
72  30072    16   1  57        0   2
73  30073    17   1  57        0   2
74  30074    18   1  57        0   2
75  30075    19   1  57        0   2
76  30076    20   1  57        0   2
77  30077    21   1  57        0   2
78  30078    22   1  57        0   2
79  30079    23   1  57        0   2
80  30080    24   1  57        0   2
81  30081    25   1  57        0   2
82  30082    26   1  57        0   2
83  30083    27   1  57        0   2
84  30084    28   1  57        0   2

[85 rows x 6 columns]

In [165]:
X_testData = test_data.iloc[:,[1, 2, 3, 4, 5]]
X_testData

職員id  続柄  生年  企業コード有無  性別
0      1   1  77        1   1
1      2   1  77        1   1
2      3   1  77        1   1
3      4   1  77        1   1
4      5   1  77        1   1
5      6   1  77        1   1
6      7   1  77        1   1
7      8   1  77        1   1
8      9   1  77        1   1
9     10   1  77        1   1
10    11   1  77        1   1
11    12   1  77        1   1
12    13   1  77        1   1
13    14   1  77        1   1
14    15   1  77        1   1
15    16   1  77        1   1
16    17   1  77        1   1
17    18   1  77        1   1
18    19   1  77        1   1
19    20   1  77        1   1
20    21   1  77        1   1
21    22   1  77        1   1
22    23   1  77        1   1
23    24   1  77        1   1
24    25   1  77        1   1
25    26   1  77        1   1
26    27   1  77        1   1
27    28   1  77        1   1
28     1   1  97        1   1
29     2   1  97        1   1
..   ...  ..  ..      ...  ..
55    28   1  97        1   1
56    28   1  84        0   1
57     1   1  57        0   2
58     2   1  57        0   2
59     3   1  57        0   2
60     4   1  57        0   2
61     5   1  57        0   2
62     6   1  57        0   2
63     7   1  57        0   2
64     8   1  57        0   2
65     9   1  57        0   2
66    10   1  57        0   2
67    11   1  57        0   2
68    12   1  57        0   2
69    13   1  57        0   2
70    14   1  57        0   2
71    15   1  57        0   2
72    16   1  57        0   2
73    17   1  57        0   2
74    18   1  57        0   2
75    19   1  57        0   2
76    20   1  57        0   2
77    21   1  57        0   2
78    22   1  57        0   2
79    23   1  57        0   2
80    24   1  57        0   2
81    25   1  57        0   2
82    26   1  57        0   2
83    27   1  57        0   2
84    28   1  57        0   2

[85 rows x 5 columns]

In [172]:
sc_testData = StandardScaler()
X_train_std = sc_testData.fit_transform(X_train)
X_testData_std = sc_testData.transform(X_testData)


In [173]:
y_pred_testData = mod.predict_proba(X_testData_std)[:,1]

In [174]:
y_pred_testData

array([ 0.06313942,  0.07349858,  0.07012478,  0.07012478,  0.08237489,
        0.08237489,  0.11386048,  0.09445133,  0.09915175,  0.04583484,
        0.04902453,  0.04902453,  0.04329804,  0.04329804,  0.05375984,
        0.05375984,  0.05375984,  0.04498738,  0.04498738,  0.04429584,
        0.04429584,  0.04374346,  0.04374346,  0.04374346,  0.04374346,
        0.04954959,  0.04954959,  0.05406707,  0.34934402,  0.41824234,
        0.42364237,  0.42364237,  0.46665639,  0.46665639,  0.60099912,
        0.56471491,  0.57788354,  0.46301839,  0.48061666,  0.48061666,
        0.42781559,  0.42781559,  0.48416668,  0.46310377,  0.46310377,
        0.36746973,  0.36746973,  0.36746973,  0.36746973,  0.36746973,
        0.36746973,  0.36746973,  0.36746973,  0.39064443,  0.39064443,
        0.50734466,  0.04701996,  0.02923015,  0.02365933,  0.02081354,
        0.02081354,  0.03846157,  0.03846157,  0.04697331,  0.02991773,
        0.02991773,  0.02796626,  0.02995149,  0.02995149,  0.02

In [180]:
from sklearn.calibration import CalibratedClassifierCV
clf_sigmoid = CalibratedClassifierCV(mod, cv=2, method='isotonic')
clf_sigmoid.fit(X_train_std, y_train)
prob_pos_sigmoid = clf_sigmoid.predict_proba(X_testData_std)[:, 1]
prob_pos_sigmoid

array([ 0.05964331,  0.0631665 ,  0.0631665 ,  0.0631665 ,  0.07861326,
        0.07861326,  0.12606391,  0.12301364,  0.12521508,  0.05395354,
        0.06552488,  0.06552488,  0.04831083,  0.04831083,  0.05395354,
        0.05395354,  0.05043034,  0.04478763,  0.03864758,  0.03864758,
        0.04217077,  0.04437072,  0.04437072,  0.04437072,  0.03534422,
        0.0501999 ,  0.05104872,  0.06401533,  0.23108413,  0.23108413,
        0.23108413,  0.23108413,  0.23108413,  0.23108413,  0.27922078,
        0.27922078,  0.27922078,  0.23108413,  0.23160173,  0.23160173,
        0.23108413,  0.23108413,  0.23108413,  0.23108413,  0.27922078,
        0.23108413,  0.17591629,  0.17591629,  0.17591629,  0.23108413,
        0.23108413,  0.23108413,  0.23108413,  0.23108413,  0.23108413,
        0.23108413,  0.05702496,  0.0166535 ,  0.0166535 ,  0.0166535 ,
        0.0166535 ,  0.04437072,  0.04437072,  0.05001344,  0.03823067,
        0.02920417,  0.02198703,  0.02883362,  0.02883362,  0.02